NAME		= Cast
SRCS		= main.cpp convert.cpp utils.cpp
CXX			= clang++
CXXFLAGS	= -Wall -Wextra -Werror
OBJS		= $(SRCS:.cpp=.o)
all:		$(NAME) $(DONE)

main.o: main.cpp convert.hpp
convert.o: convert.cpp convert.hpp
utils.o: utils.cpp convert.hpp

$(NAME):	$(OBJS)
			$(CXX) $(CXXFLAGS) $(OBJS) -I. -o $(NAME)

clean:
			rm -rf $(OBJS)

fclean:		clean
			rm -rf $(NAME)
			rm -rf *.d


re:			fclean all

.PHONY:		all clean fclean re